### ISSUE TITLE
Day 5 contains Day 4's puzzle description

### ISSUE THREAD

**Issue by KyranRana** [antoligy/advent-of-code#1]
That doesn't seem right, the readme.md is duplicated 👍 

I've done both AoC 2015 and 2016. FYI if you continue, Day 11 is the hardest by far...

**Comment by alexwilson** [comment]
Oof, nice catch, totally forgot about that one.

**Comment by alexwilson** [comment]
Thanks for that!

Will probably continue on with AoC 2016 once I find some time - @mikotohe2 totally bailed so I sort-of stopped midway.  

Day 11 looks fun!
